import "./styles/globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from "./components/header";
import WalletProvider from "@/utils/walletProvider";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "OpenSui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletProvider>
          <Header />
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
